# Xeon Series
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/240357/intel-xeon-6.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/236644/5th-gen-intel-xeon-scalable-processors.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/228622/4th-gen-intel-xeon-scalable-processors.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/204098/3rd-gen-intel-xeon-scalable-processors.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/192283/2nd-gen-intel-xeon-scalable-processors.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/125191/intel-xeon-scalable-processors.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/232643/intel-xeon-cpu-max-series.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/134861/intel-xeon-e-processor.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/125035/intel-xeon-w-processor.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/87041/intel-xeon-d-processor.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/93797/intel-xeon-processor-e7-v4-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/78585/intel-xeon-processor-e7-v3-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/78584/intel-xeon-processor-e7-v2-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/59139/intel-xeon-processor-e7-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/91287/intel-xeon-processor-e5-v4-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/78583/intel-xeon-processor-e5-v3-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/78582/intel-xeon-processor-e5-v2-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/59138/intel-xeon-processor-e5-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/97141/intel-xeon-processor-e3-v6-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/88210/intel-xeon-processor-e3-v5-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/87722/intel-xeon-processor-e3-v4-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/78581/intel-xeon-processor-e3-v3-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/78580/intel-xeon-processor-e3-v2-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/59137/intel-xeon-processor-e3-family.html"
scrapy crawl series -a url="https://ark.intel.com/content/www/us/en/ark/products/series/59213/legacy-intel-xeon-processors.html"

